// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// dynNetModelSamp
Rcpp::List dynNetModelSamp(NumericVector y, arma::mat X, double lambda, double k, double tau, double a, arma::vec nu, arma::vec rho, arma::mat B, NumericMatrix dataTimeLocs, int nBurn, int nSamp, int nThin);
RcppExport SEXP _SBDN_dynNetModelSamp(SEXP ySEXP, SEXP XSEXP, SEXP lambdaSEXP, SEXP kSEXP, SEXP tauSEXP, SEXP aSEXP, SEXP nuSEXP, SEXP rhoSEXP, SEXP BSEXP, SEXP dataTimeLocsSEXP, SEXP nBurnSEXP, SEXP nSampSEXP, SEXP nThinSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type B(BSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dataTimeLocs(dataTimeLocsSEXP);
    Rcpp::traits::input_parameter< int >::type nBurn(nBurnSEXP);
    Rcpp::traits::input_parameter< int >::type nSamp(nSampSEXP);
    Rcpp::traits::input_parameter< int >::type nThin(nThinSEXP);
    rcpp_result_gen = Rcpp::wrap(dynNetModelSamp(y, X, lambda, k, tau, a, nu, rho, B, dataTimeLocs, nBurn, nSamp, nThin));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SBDN_dynNetModelSamp", (DL_FUNC) &_SBDN_dynNetModelSamp, 13},
    {NULL, NULL, 0}
};

RcppExport void R_init_SBDN(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
