# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dynNetModelSamp <- function(y, X, lambda, k, tau, a, nu, rho, B, dataTimeLocs, nBurn, nSamp, nThin) {
    .Call('_SBDN_dynNetModelSamp', PACKAGE = 'SBDN', y, X, lambda, k, tau, a, nu, rho, B, dataTimeLocs, nBurn, nSamp, nThin)
}

